improve function construct_url. validate date in post file

diff --git a/squib b/squib
--- a/squib
+++ b/squib
@@ -1,4 +1,7 @@
-#!/bin/bash -e
+#!/bin/bash
+
+set -o errexit
+set -o pipefail
 
 # Squib - A Static Site Generator
 
@@ -21,6 +24,7 @@ squib_pagination_url="/blog"
 
 readonly clr_cyan='\033[36m'
 readonly clr_yellow="\033[33m"
+readonly clr_red="\033[0;31m"
 readonly clr_none='\033[0m' # No color
 
 # Defaults
@@ -46,8 +50,20 @@ log::std() {
 }
 
 log::warn() {
-    # Usage: log::warn "Danger Will Robinson"
-    log::std "${clr_yellow}WARN:${clr_none} $*"
+    # Usage: log::warn "Will Robinson"
+    log::std "${clr_yellow}DANGER:${clr_none} $*"
+}
+
+log::error() {
+    # Usage: log::error "Whoooops something went wrong"
+    log::std "${clr_red}ERROR:${clr_none} $*"
+}
+
+log::fatal() {
+    # Usage: log::fatal "Whoooops something went wrong"
+    log::std "${clr_red}FATAL ERROR:${clr_none} $*"
+
+    kill $$ &> /dev/null
 }
 
 log::debug() {
@@ -327,12 +343,11 @@ post::lookup_url() {
 
 post::construct_url() {
     local post=$(util::basename "$1")
+    local regex_valid_date="^([0-9]{4})\-([0-9]{2})\-([0-9]{2})$"
 
     # Posts must adhere to either of the two naming conventions:
     # posts/YYYY-MM-DD-hello-world.md
     # posts/YYYY-MM-DD-hello-world.html
-
-    # TODO: add regex to check filename format is correct
 
     # post::construct_url splits a post's filename into two parts:
     # ---------------------------------------------------------------------------
@@ -340,7 +355,13 @@ post::construct_url() {
     # $pagination_url/YYYY-MM-DD<foobar>.md
     #                 ^^^^^^^^^^
 
-    # 2. The slug
+    # 2. The delimiter
+    # This is a single character and can equal anything. But to keep thing
+    # simple use '-'. This is sits betweeen the date and slug.
+    # $pagination_url/YYYY-MM-DD-Hello-World.html
+    #                           ^
+
+    # 3. The slug
     # This is everything that precedes 'YYYY-MM-DD-'
     # $pagination_url/YYYY-MM-DD-Hello-World.html
     #                            ^^^^^^^^^^^^^^^^
@@ -348,9 +369,15 @@ post::construct_url() {
     # Using substrings is prefered over splitting 'path' into an array delimited
     # by '-', since the slug could contain additional hyphens.
 
-    local post_timestamp=${post:0:10} # The timestamp length is a fixed.
+    local post_timestamp=${post:0:10} # The timestamp length is fixed.
+    if [[ ! "$post_timestamp" =~ ^([0-9]{4})\-([0-9]{2})\-([0-9]{2}) ]]; then
+        log::warn "post '$post' is not formatted correctly. Filename must be prefixed with: 'YYYY-MM-DD-'"
+        return 1
+    fi
+
     local post_slug=${post:11} # TODO: downcase and run against urlencode
     [[ "$post_slug" == *.md ]] && post_slug=$(string::rstrip "$post_slug" ".md").html # duplicate code
+    post_slug="$(util::urlencode ${post_slug,,})" # Downcase, and encode
 
     # /year/month/day/slug.html
     printf '%s\n' "${squib_base_url}${squib_pagination_url}/${post_timestamp:0:4}/${post_timestamp:5:2}/${post_timestamp:8:2}/$post_slug"
@@ -364,7 +391,7 @@ post::render_links() {
         readarray -t front_matter < <(page::collect_front_matter "$post")
         if [[ $? -ne 0 ]]; then
             log::warn "function 'page::collect_front_matter' returned non-zero code."
-            return
+            return 1
         fi
 
         # We really only need 'title' and 'draft', but we eval everything just
@@ -385,8 +412,7 @@ post::render_links() {
 
         post_relative_url=$(post::construct_url "$post")
         if [[ $? -ne 0 ]]; then
-            log::warn "function 'post::construct_url' returned non-zero code."
-            return 1
+            log::fatal "function 'post::construct_url' returned non-zero code."
         fi
 
         local tmp post_timestamp
@@ -408,7 +434,7 @@ watch::generate_hashes() {
     # Usage: watch::generate_hashes
 
     if [[ -n "$1" ]]; then
-        log::warn "func '${FUNCNAME[0]}' does not support arguments."
+        log::warn "function '${FUNCNAME[0]}' does not support arguments."
         return 1
     fi
 
@@ -424,8 +450,7 @@ watch::generate_hash() {
     # Usage: watch::generate_hash <path/to/file>
 
     if [[ -n "$2" ]]; then
-        log::warn "Whoa.. func '${FUNCNAME[0]}' called with more than one argument."
-        return 1
+        log::fatal "function '${FUNCNAME[0]}' called with more than one argument."
     fi
 
     # Thoughts
@@ -723,8 +748,7 @@ build::all() {
 
     readonly squib_post_html_tags="<ul>$(post::render_links)</ul>"
     if [[ $? -ne 0 ]]; then
-        log::warn "function 'post::render_links' returned non-zero code."
-        return 1
+        log::fatal "function 'post::render_links' returned non-zero code."
     fi
 
     prep::all
@@ -745,8 +769,7 @@ main() {
             build::all
             ;;
         *)
-            log::warn "Unsupported action: '$action'"
-            exit 1
+            log::fatal "Unsupported action: '$action'"
             ;;
     esac
 }
